"""End-to-end: load YAML seeds → decompose → consolidate → render viz.

Steps:
  1. Parse design_docs/internal_links_seed_v0.yaml
  2. For each entry, upsert StateBelief and InternalLink records into Neo4j
  3. Run BeliefDecomposer over the seed premises (budget=100 Sonnet calls)
  4. Run consolidate() on the resulting graph
  5. Render the static-network viz

After this script: Neo4j has the full hand-seeded + decomposed + consolidated
belief network, and viz_beliefs/latest.html shows it.
"""
from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path

ROOT = Path("/home/dgonier/ecology_experiment/trophic")
sys.path.insert(0, str(ROOT))

# Load .env
env = ROOT / ".env"
if env.exists():
    for line in env.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k = k.strip(); v = v.strip().strip('"').strip("'")
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k):
            continue
        os.environ.setdefault(k, v)

import yaml

from trophic.beliefs import (
    InternalLink,
    ModalEmbedder,
    OutcomeBelief,
    StateBelief,
    consolidate,
    render_pass_viz,
    snapshot_pass,
)
from trophic.beliefs.decomposer import BeliefDecomposer
from trophic.beliefs.neo4j_store import Neo4jBeliefStore


YAML_PATH = ROOT / "design_docs" / "internal_links_seed_v0.yaml"


def hr() -> None:
    print("─" * 70)


def _belief_kind(entry: dict) -> str:
    """Distinguish a state-belief entry from a link entry by required fields."""
    if entry.get("kind") == "state_belief":
        return "state_belief"
    if "premise_belief_id" in entry and "conclusion_belief_id" in entry:
        return "link"
    if "statement_template" in entry:
        return "state_belief"
    return "unknown"


def _ensure_state_belief(
    store: Neo4jBeliefStore, belief_id: str, scope: str = "company",
    statement: str = "(autogenerated stub)",
    polymarket_market_id: str = None,
) -> None:
    """Upsert a stub StateBelief if one doesn't exist. Used for premise/conclusion
    references that the YAML doesn't explicitly declare as state_belief entries.
    """
    existing = store.get_state_belief(belief_id)
    if existing is not None:
        return
    if belief_id.startswith("outcome."):
        return  # outcome beliefs created separately
    sb = StateBelief(
        id=belief_id,
        statement_template=statement,
        scope=scope,
        prior_p=0.5,
        current_p=0.5,
        decay_class="normal",
        last_updated=time.time(),
        polymarket_market_id=polymarket_market_id,
    )
    store.upsert_state_belief(sb)


def _ensure_outcome(store: Neo4jBeliefStore, outcome_id: str) -> None:
    """Upsert a placeholder outcome if the link references one."""
    if not outcome_id.startswith("outcome."):
        return
    # OutcomeBelief gets created on demand at scenario-time. Here we
    # MERGE a stub so the link.LINKS_TO edge has a target.
    parts = outcome_id.split(".")
    ticker = parts[1] if len(parts) > 1 else "UNKNOWN"
    o = OutcomeBelief(
        id=outcome_id,
        ticker=ticker,
        horizon_min=1440,
        statement=f"{ticker} closes up tomorrow",
        p_up=0.5,
        activated_at=time.time(),
    )
    store.append_outcome_belief(o)


# ─────────────────────────────────────────────────────────────
# Step 1: load YAML
# ─────────────────────────────────────────────────────────────

def load_seed_yaml(path: Path) -> tuple[list[StateBelief], list[InternalLink]]:
    """Parse the seed inventory YAML into typed objects."""
    with path.open() as f:
        entries = yaml.safe_load(f)
    if not isinstance(entries, list):
        raise ValueError(f"expected YAML list at top level, got {type(entries)}")

    state_beliefs: list[StateBelief] = []
    links: list[InternalLink] = []
    now = time.time()
    for ent in entries:
        kind = _belief_kind(ent)
        if kind == "state_belief":
            sb = StateBelief(
                id=ent["id"],
                statement_template=ent["statement_template"],
                scope=ent["scope"],
                prior_p=float(ent.get("prior_p", 0.5)),
                current_p=float(ent.get("prior_p", 0.5)),
                decay_class=ent.get("decay_class", "normal"),
                context=ent.get("context") or {},
                last_updated=now,
                polymarket_market_id=ent.get("polymarket_market_id"),
            )
            state_beliefs.append(sb)
        elif kind == "link":
            ln = InternalLink(
                id=ent["id"],
                premise_belief_id=ent["premise_belief_id"],
                conclusion_belief_id=ent["conclusion_belief_id"],
                scope=ent["scope"],
                direction=ent["direction"],
                strength_prior=float(ent.get("strength_prior", 0.5)),
                strength_posterior=float(ent.get("strength_prior", 0.5)),
                citation=ent.get("citation", ""),
                created_at=now, updated_at=now,
            )
            links.append(ln)
    return state_beliefs, links


# ─────────────────────────────────────────────────────────────
# Step 2: persist into Neo4j
# ─────────────────────────────────────────────────────────────

def upsert_seeds(
    store: Neo4jBeliefStore,
    state_beliefs: list[StateBelief],
    links: list[InternalLink],
) -> None:
    """Upsert state beliefs first, then auto-create stub state beliefs and
    outcomes for any premise/conclusion that wasn't declared, then upsert links.
    """
    for sb in state_beliefs:
        store.upsert_state_belief(sb)

    declared_ids = {sb.id for sb in state_beliefs}
    for l in links:
        # Stub premise if not declared
        if l.premise_belief_id not in declared_ids and not l.premise_belief_id.startswith("outcome."):
            _ensure_state_belief(
                store, l.premise_belief_id, scope=l.scope,
                statement=f"(stub for {l.premise_belief_id})",
            )
            declared_ids.add(l.premise_belief_id)
        # Stub conclusion if outcome
        if l.conclusion_belief_id.startswith("outcome."):
            _ensure_outcome(store, l.conclusion_belief_id)
        elif l.conclusion_belief_id not in declared_ids:
            _ensure_state_belief(
                store, l.conclusion_belief_id, scope=l.scope,
                statement=f"(stub for {l.conclusion_belief_id})",
            )
            declared_ids.add(l.conclusion_belief_id)

    for l in links:
        store.upsert_link(l)


# ─────────────────────────────────────────────────────────────
# Cleanup helper for re-runs
# ─────────────────────────────────────────────────────────────

def cleanup_ecology_namespace(store: Neo4jBeliefStore, *, dry_run: bool = False) -> int:
    """Wipe everything in the :Ecology namespace before reseeding. Bounded
    cleanup — only touches our namespace, leaves DebaterHub/Hexis alone."""
    with store.driver.session() as sess:
        before = sess.run("MATCH (n:Ecology) RETURN count(n) AS n").single()["n"]
        if dry_run:
            print(f"  [dry-run] would delete {before} Ecology nodes")
            return before
        sess.run("MATCH (n:Ecology) DETACH DELETE n")
        return before


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(
        description="Load YAML seeds → decompose → consolidate → render viz"
    )
    ap.add_argument(
        "--reset", action="store_true",
        help="Wipe the :Ecology namespace before seeding. Default is "
             "incremental: keep existing decompositions, only fill gaps.",
    )
    ap.add_argument(
        "--max-calls", type=int, default=200,
        help="Decomposer LLM call budget (default 200, was 100). With "
             "parallel calls this finishes in ~1-2 min.",
    )
    ap.add_argument(
        "--max-workers", type=int, default=8,
        help="Thread pool size for parallel Bedrock + Modal calls.",
    )
    ap.add_argument(
        "--skip-decompose", action="store_true",
        help="Only run consolidation + viz; skip decomposer (assumes prior "
             "run already decomposed).",
    )
    ap.add_argument(
        "--max-judge-calls", type=int, default=100,
        help="Hard cap on consolidator LLM judge calls (default 100). "
             "Borderline pairs are sorted by descending cosine; we judge "
             "the highest-similarity ones first up to this cap.",
    )
    ap.add_argument(
        "--skip-consolidate", action="store_true",
        help="Skip consolidation; just decompose + viz.",
    )
    args = ap.parse_args()

    print("Seeding belief network end-to-end\n")

    # 0. Connect
    store = Neo4jBeliefStore()
    print(f"connected: {os.environ['NEO4J_URI']}")

    if args.reset:
        n_wiped = cleanup_ecology_namespace(store)
        print(f"--reset: wiped {n_wiped} prior Ecology nodes (clean slate)")
    else:
        n_existing = len(store.all_state_beliefs())
        print(f"incremental run: {n_existing} existing :Ecology beliefs in store; "
              f"will resume rather than wipe (use --reset to start fresh)")
    hr()

    # 1. Load + 2. Upsert seeds
    print(f"loading YAML: {YAML_PATH.relative_to(ROOT)}")
    state_beliefs, links = load_seed_yaml(YAML_PATH)
    print(f"  state beliefs: {len(state_beliefs)}")
    print(f"  links:         {len(links)}")
    upsert_seeds(store, state_beliefs, links)
    n_after_seed = len(store.all_state_beliefs())
    n_links_after = len(store.all_links())
    print(f"  upserted: {n_after_seed} state beliefs, {n_links_after} links")
    hr()

    # 3. Decompose (skippable)
    decomp_stats = None
    if args.skip_decompose:
        print("--skip-decompose: skipping decomposer pass")
    else:
        print(f"running BeliefDecomposer (Bedrock Sonnet, "
              f"budget={args.max_calls} calls, max_depth=5, max_workers={args.max_workers})")
        decomposer = BeliefDecomposer(
            store=store, max_depth=5,
            max_calls=args.max_calls, max_workers=args.max_workers,
        )
        decomp_stats = decomposer.decompose_all_seed_premises(links)
        print()
        print(f"  LLM calls:                    {decomp_stats.n_llm_calls}")
        print(f"  intermediate beliefs added:   {decomp_stats.n_intermediate_beliefs}")
        print(f"  links added:                  {decomp_stats.n_links_created}")
        print(f"  terminal leaves:              {decomp_stats.n_terminal_leaves}")
        print(f"  max depth reached:            {decomp_stats.max_depth_reached}")
        print(f"  budget exhausted:             {decomp_stats.budget_exhausted}")
        n_after_decompose = len(store.all_state_beliefs())
        n_links_after_decompose = len(store.all_links())
        print(f"  network now: {n_after_decompose} beliefs, {n_links_after_decompose} links")
    hr()

    # 4. Consolidate (skippable)
    cons_report = None
    if args.skip_consolidate:
        print("--skip-consolidate: skipping consolidation pass")
    else:
        print(f"running consolidate() (Modal embeddings + Bedrock Sonnet judge "
              f"on borderline, max_workers={args.max_workers})")
        embedder = ModalEmbedder()
        cons_report = consolidate(
            store, embedder=embedder,
            llm_judge_borderline=True, apply=True,
            max_workers=args.max_workers,
            max_judge_calls=args.max_judge_calls,
            verbose=True,
        )
        print()
        print(f"  pairs evaluated:    {cons_report.n_pairs_evaluated}")
        print(f"  lexical merges:     {cons_report.n_lexical_merges}")
        print(f"  embedding merges:   {cons_report.n_embedding_merges}")
        print(f"  llm borderline:     {cons_report.n_llm_borderline}")
        print(f"  llm confirmed:      {cons_report.n_llm_confirmed}")
        print(f"  llm rejected:       {cons_report.n_llm_rejected}")
        print(f"  llm calls (judge):  {cons_report.n_llm_calls}")
        print(f"  merges applied:     {len(cons_report.merges_applied)}")
    n_final_beliefs = len(store.all_state_beliefs())
    n_final_links = len(store.all_links())
    print(f"  network now: {n_final_beliefs} beliefs, {n_final_links} links")
    hr()

    # 5. Render viz
    print("rendering viz")
    snap = snapshot_pass(
        store=store,
        pass_id="seed_network",
        pass_meta={
            "ticker": "(static seed)",
            "scenario": "post-decompose-consolidate",
            "label": "(no events yet)",
            "prediction": None,
        },
        incoming_events=None,
        outcome_predictions=None,
    )
    out_dir = ROOT / "viz_beliefs"
    json_path, html_path = render_pass_viz(snap, out_dir, pass_id="seed_network")

    hr()
    print(f"\n=== TOTAL ===")
    print(f"  seed beliefs (YAML):              {len(state_beliefs)}")
    print(f"  seed links (YAML):                {len(links)}")
    if decomp_stats is not None:
        print(f"  decomposer LLM calls:             {decomp_stats.n_llm_calls}")
    if cons_report is not None:
        print(f"  consolidator LLM calls:           {cons_report.n_llm_calls}")
    if decomp_stats is not None and cons_report is not None:
        print(f"  TOTAL LLM calls:                  "
              f"{decomp_stats.n_llm_calls + cons_report.n_llm_calls}")
    print(f"  final beliefs in store:           {n_final_beliefs}")
    print(f"  final links in store:             {n_final_links}")
    if decomp_stats is not None:
        print(f"  max depth reached:                {decomp_stats.max_depth_reached}")
    print(f"\n  viz: file://{html_path.resolve()}")
    print(f"  latest: file://{(out_dir / 'latest.html').resolve()}")

    store.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
